apiVersion: apps/v1
kind: Deployment # kind
metadata:
    name: fastapi-deployment # name of deployment
    labels:
        app: fastapi
spec: # specs for deployment
    replicas: 3
    selector:
        matchLabels:
            app: fastapi
    template:
        metadata:
            labels:
                app: fastapi
        spec: # specs for each pod
            containers:
                - name: fastapi
                  image: tiangolo/uvicorn-gunicorn-fastapi:python3.11-slim-2023-09-11
                  ports:
                      - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
    name: fastapi-svc
spec:
    selector:
        app: fastapi
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 9376
          targetPort: 80