[project]
name = "mlops-week4"
version = "0.1.0"
description = "purpose:usage of lightning modules with uv, dev containers"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lightning[extra]==2.4.0",
    "torch==2.4.1",
    "torchvision==0.19.1",
]
