defaults:
  - _self_
  - data: dogbreed
  - model: dogbreed_classifier
  - logger : default
  - paths : default
  - callbacks: default
  - trainer : default
  # - hparams: dogbreed_ex_vit_hparam

task_name : training
train: true
test : false
