# csv logger built in lightning

comet:
  _target_: lightning.pytorch.loggers.CometLogger
  save_dir: "${paths.output_dir}"
  experiment_name: "${paths.output_dir}_${now:%Y-%m-%d_%H-%M-%S}"
  api_key: "p1DteVPrPThJCilEB9sjqgvr9"
  workspace: "anvesh-vankayala"