# MLflow logger configuration

mlflow:
  _target_: lightning.pytorch.loggers.MLFlowLogger
  experiment_name: "dog_breed_exp"
  tracking_uri: file:${paths.log_dir}/mlruns
  save_dir: ${paths.log_dir}/mlruns
  log_model: False
  prefix: ""